### ISSUE TITLE
[Issue] User Management: Update a user via the API

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/cpf-reporter#102]
**Subtask of user story:** User Management https://github.com/usdigitalresponse/cpf-reporter/issues/81

**DOD:** A `createUser` graphQL mutation resolver exists which allows authorized users to modify existing users via the API

**Blocked by issues:**
- https://github.com/usdigitalresponse/cpf-reporter/issues/103

**Blocks these issues:**
- https://github.com/usdigitalresponse/cpf-reporter/issues/106
- https://github.com/usdigitalresponse/cpf-reporter/issues/107

**Implementation Details:**
- Define an `UpdateUserInput` input type in `users.sdl.ts` that implements the following data model, per the `User` Prisma model:
  - `name`: string, optional
  - `agencyId`: int, optional
  - `role`: enum `RoleEnum`, one of `USDR_ADMIN`, `ORGANIZATION_ADMIN`, `ORGANIZATION_STAFF`, optional
  - `isActive`: boolean, optional
- Ensure that the gql schema in users.sdl.ts implements a mutation for updateUser that:
  - Accepts input conforming to the `UpdateUserInput` input schema
  - Uses the `@requireAuth` directive to restrict access to authenticated users with a role of `USDR_ADMIN` or `ORGANIZATION_ADMIN`.
- Define an API-side `users` service with an `updateUser` mutation resolver which satisfies the following scenarios:
    - _Note: use [service validations](https://redwoodjs.com/docs/canary/services#service-validations) to validate input and other user creation constraints. Relevant service validations are linked below._
    - Users may only be updated when the following input conditions are satisfied:
      - `name` must [not be null](https://redwoodjs.com/docs/services#presence)
      - `role` must [not be null](https://redwoodjs.com/docs/services#presence) and must be a valid `UserRole` enum
      - `agencyId` must refer to an [existing agency](https://redwoodjs.com/docs/services#validatewith)
    - Requests made by a user with role `USDR_ADMIN` should be able to update a user of any role for any organization
    - Requests made by a user with role `ORGANIZATION_ADMIN` should be able to create a user of any role in the same organization as the authenticated user, but not for any other organization. Note that this must be determined via the `agency` relationship of both users, e.g.
       ```js
       // Assume `currentUser` has `.agency.organizationId` loaded
       validateWith(async () => {
         if (input.agencyId === undefined) { return }
         const targetUserOrgId = (await db.agency.findUniqueOrThrow({
           where: { id: input.agencyId },
           select: { organizationId: true },
         })).organizationId
         if (targetUserOrgId !== currentUser.agency.organizationId) {
           throw new Error("You don't have permission to do that")
         }
       })
       ```
    - Changes to `agencyId` are only allowed if the new/target agency identified in the update input belongs to the same organization as the user's current/previous agency, e.g.
       ```js
       validateWith(async () => {
         if (input.agencyId === undefined) { return }
         const currentAgency = (await db.user.findUniqueOrThrow({
           where: { id: id },
           select: { agency: { select: { id: true, organizationId: true }}},
         })).agency
         if (input.agencyId === currentAgency.id) { return }
         try {
           await db.agency.findUniqueOrThrow({
             where: { id: input.agencyId, organizationId: currentAgency.organizationId },
           })
         } catch (err) {
           // Consider also including IDs for user, current agency, and new agency in the structured log data
           log.error({ err }, 'change to user.agencyId is not allowed')
           throw new Error('agencyId is invalid or unavailable to this user')
         }
       })
       ```

**Comment by laurelkorwin** [comment]
@as1729 Can you confirm if we want the same basic validations on name, email and role for both create as well as update? I noticed `createUser` has a validation on email (whereas this ticket doesn't specify), and this ticket has a role validation whereas `createUser` does not. I'd be inclined to make a common method for both w/those three criteria, but not sure if I am missing intended behavior :)

**Comment by as1729** [comment]
@laurelkorwin good point- the validations should be identical for both create and update 👍

**Comment by laurelkorwin** [comment]
Also, noodling over permissions in my head and wanted to clarify -- it seems like:
- `USDR_ADMIN` should be able to create / update any type of user, for any org, for any role:
- `ORGANIZATION_ADMIN` should be able to create / update users of any role _except_ for `USDR_ADMIN`, for any agency where the new agency id is part of their organization
- `ORGANIZATION_STAFF` should not be able to create / update users at all.

**Comment by as1729** [comment]
Yup that summary is correct
