### ISSUE TITLE
[Issue] User Management: Update `User` Prisma model

### ISSUE THREAD

**Issue by TylerHendrickson** [usdigitalresponse/cpf-reporter#103]
**Subtask of user story:** User Management https://github.com/usdigitalresponse/cpf-reporter/issues/81

**DOD:** The `User` Prisma model is updated to only implement direct relations and make required foreign keys non-nullable. 

**Blocked by issues:** (None)
**Blocks these issues:**
- https://github.com/usdigitalresponse/cpf-reporter/issues/101
- https://github.com/usdigitalresponse/cpf-reporter/issues/102

**Implementation details:**
- Define a `User` Prisma model that implements the following schema:
  - Columns:
    - `id`: Int, pk
    - `email`: string, valid email address, required, add unique
    - `name`: string, required
    - `agencyId`: int, fk to `Agency.id`, **required**
    - `createdAt`: DateTime with timezone, default `now()`, required
    - `updatedAt`: DateTime with timezone, default `now()`, required
    - `role`: value of `Role` enum, required
    - `isActive`: boolean, default `true`, required
  - Relations: 
    - `agency`: 
      - type `Agency` 
      - via `User.agencyId` referencing `Agency.id`
    - `certified`: 
      - type `[]ReportingPeriod` (to-many) 
      - via `ReportingPeriod.certifiedById` referencing `User.id`
    - `uploaded`: 
      - type `[]Upload` (to-many) 
      - via `Upload.uploadedById` referencing `User.id`
- [Seed development fixtures](https://redwoodjs.com/docs/canary/cli-commands#prisma-db-seed) for each user role (and dependencies thereof, e.g. `Agency` and `Organization`) in `scripts/seed.ts`
  - Fixtures that can successfully seed a development environment will suffice in lieu of unit tests for this issue.

**Comment by as1729** [comment]
@TylerHendrickson for valid email validation, do we want to enforce this in the backend and database layer or is it sufficient to handle on the front-end?
