### ISSUE TITLE
[Issue]: Uploads table not displaying

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#133]
### Why is this issue important?

We need the uploads table to display for users to be able to see their uploads. 

### Current State

The [Uploads page ](https://staging.cpf.usdr.dev/) shows the following:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/39427d14-041a-4334-8e36-1874f2d71767)

### Expected State

The uploads page should show a table of uploads: 

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/1f2fd603-75f0-41d4-a693-973005953735)

### Implementation Plan

@as1729

**Comment by as1729** [comment]
This is resolved. The solution here was to run migrations in the staging database. There is no code change required.
