### ISSUE TITLE
User Management: Users page / Viewing Users functionality

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#14]
### Why is this issue important?
This is a part of the [User Management User Story](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=50424619).
This work takes place primarily under the Users tab of the webapp. The first step to building this functionality is building out the users page and table, which allows for the Viewing Users functionality.

### Current State

None

### Expected State

The Users tab and associated functionality should only be accessible to admin users. Clicking on the Users tab should bring the user to the Users page. In the Users page, they should see a table of all current users in their tenant’s organization: 

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/6d93129a-059f-4d13-93bb-ebc3eb318419)

This page should include:

- page title of “Users”
- “Create New User” Button [this ticket does not include New User implementation, the button just needs to be made. New User Implementation is part of [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44763683)]
- Table of existing users
  - Search capability
  - Columns:
  - Email
  - Name
  - Role: Staff or Admin
  - Agency
  - Created: Creation time / date
  - Edit: Edit button for individual user [this ticket does not include edit implementation, the button just needs to be made. edit button implementation is on [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44764610)]

The user should be able to sort the table by each column. Users should be able to use the search capability or sort by each column to find users.

### Implementation Plan

Data-model: 
https://lucid.app/lucidchart/93e8fea1-fd5b-4722-901b-cfe6703f3798/edit?invitationId=inv_ca230f47-f1bf-4594-a959-696293102dbf&page=0_0#

CRUD page creation:
Cells to view data: https://redwoodjs.com/docs/tutorial/chapter2/cells
Forms to accept data: https://redwoodjs.com/docs/tutorial/chapter3/forms

**Comment by as1729** [comment]
Related to #15 and #16 please work on the three together.

**Comment by ClaireValdivia** [comment]
Tested in staging and this is looking great on the usdr admin role - will create an issue for making the User tab visible to Org Admins
