### ISSUE TITLE
User Management: Adding Users functionality

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#15]
### Why is this issue important?
This is a part of the [User Management User Story](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=50424619).
One of the tasks within this user story is Adding Users. Building out the adding users functionality is a necessary element of the CPF reporter. Dependent on [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44762614).

### Current State

None

### Expected State

This functionality should only be accessible to admin users. Clicking on the “Create New User” button should lead to the Create New User page:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/55fecdb2-4485-4cd5-94c2-81e1130548de)

This page includes the following:

- Page title of “User”
- Frozen ID textbox
- Email textbox
- Name textbox
- Role dropdown with 2 options: staff or admin
- Agency dropdown with existing agencies in the tenant as options
- Reset button: clears all entered information
- Save button: adds a user based on entered information
  - Email, name, role, and agency are required fields. If any of these is missing, an error message will appear under the missing field textboxes and the user will not be saved.

Saving a user adds them to the database, and therefore the table, of users and creates a user account for them. This allows the user to login with their associated email.

### Implementation Plan

Data-model: 
https://lucid.app/lucidchart/93e8fea1-fd5b-4722-901b-cfe6703f3798/edit?invitationId=inv_ca230f47-f1bf-4594-a959-696293102dbf&page=0_0#

CRUD page creation:
Cells to view data: https://redwoodjs.com/docs/tutorial/chapter2/cells
Forms to accept data: https://redwoodjs.com/docs/tutorial/chapter3/forms

**Comment by as1729** [comment]
Recommend to work on #16 together with this ticket.

**Comment by ClaireValdivia** [comment]
This is working great in staging. Closing ticket!
