### ISSUE TITLE
User Management: Editing Users functionality

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#16]
### Why is this issue important?
This is a part of the [User Management User Story](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=50424619).

A task within this story is Adding Users. Building out the adding users functionality is a necessary element of the CPF reporter. Dependent on [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44762614) and [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44763683).

### Current State

None

### Expected State

This functionality should only be accessible to admin users. Clicking on the “Edit” button in a row of the User table leads to the selected User’s page. This is the same page as the Create New User page, but all of the User’s existing information will be displayed:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/ecfe0961-8283-4ff0-abd9-d86e01c5e598)

Here, the user should be able to edit all the information beside the ID number, and click the Save button to save their changes. These changes should be reflected in the table of users.

### Implementation Plan

Same as #15 

Data-model:
https://lucid.app/lucidchart/93e8fea1-fd5b-4722-901b-cfe6703f3798/edit?invitationId=inv_ca230f47-f1bf-4594-a959-696293102dbf&page=0_0#

CRUD page creation:
Cells to view data: https://redwoodjs.com/docs/tutorial/chapter2/cells
Forms to accept data: https://redwoodjs.com/docs/tutorial/chapter3/forms

**Comment by as1729** [comment]
Recommend to work on #15  together with this ticket.

**Comment by ClaireValdivia** [comment]
This is working great in staging
