### ISSUE TITLE
Agency Report Submission - migrate cpfValidation code into excelToJson

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/cpf-reporter#162]
### Why is this issue important?

See User Story here https://github.com/usdigitalresponse/cpf-reporter/issues/73

This is an issue in the sequence of tickets to ensure the CPF reporter can accept a user-submitted upload file and receive feedback on any errors that are present in the submitted file data.

### Current State

There is code in `cpfValidation` javascript lambda function has working code. However, we are deprecating this javascript function in favor of the new python implementation.

### Expected State

Migrate the code in `cpfValidation` javascript lambda function into the `excelToJson` lambda function. Delete the old javascript `cpfValidation` code.

### Acceptance Criteria
- Tests must be running and passing
- `excelToJson` lambda function should be deployed to the staging environment
- `excelToJson` lambda function should respond to S3 events when `.json` files are created.

### Implementation Plan
Replace the following files:
- Copy contents from: [cpfValidation.scenarios.ts](https://github.com/usdigitalresponse/cpf-reporter/blob/main/api/src/functions/cpfValidation/cpfValidation.scenarios.ts) into [excelToJson.scenarios.ts](https://github.com/usdigitalresponse/cpf-reporter/blob/main/api/src/functions/excelToJson/excelToJson.scenarios.ts)
- Copy contents from: [cpfValidation.test.ts](https://github.com/usdigitalresponse/cpf-reporter/blob/main/api/src/functions/cpfValidation/cpfValidation.test.ts) into: [excelToJson.test.ts](https://github.com/usdigitalresponse/cpf-reporter/blob/main/api/src/functions/excelToJson/excelToJson.test.ts)
- Copy contents from: [cpfValidation.ts](https://github.com/usdigitalresponse/cpf-reporter/blob/main/api/src/functions/cpfValidation/cpfValidation.ts) into:  [excelToJson.ts](https://github.com/usdigitalresponse/cpf-reporter/blob/main/api/src/functions/excelToJson/excelToJson.ts)

**Comment by jakekreider** [comment]
So excelToJson will have the logic from cpfValidation, is that right @as1729?

**Comment by as1729** [comment]
That is correct. We would need to update the terraform to now listen to events when a `.json` file is being added instead of listen for `.xlsm` files. Otherwise we can keep the name the same with the new logic.
