### ISSUE TITLE
Agency Management: Editing Agencies functionality

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#18]
### Why is this issue important?

One of the epics of the CPF reporter is user management. One of the stories within this epic is Adding Users. Building out the adding users functionality is a necessary element of the CPF reporter. Dependent on [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44877188) and [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44877741).

### Current State

None

### Expected State

This functionality should only be accessible to admin users. Clicking on the “Edit” button in a row of the Agency table leads to the selected Agency’s page. This is the same page as the Create New Agency page, but all of the selected Agency’s existing information will be displayed:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/926170cd-f32b-4bbb-af8f-8fc8d30d0593)

- Frozen ID textbox
- Agency Code textbox
- Agency Name textbox
- Reset button: resets all entered information to the last saved values
- Save button: adds an Agency based on entered information
  - If all fields are not filled out, an error message will appear under the missing field textboxes and the agency will not be saved

Here, users should be able to edit Agency Code and Agency Name fields. Clicking save should save their changes to the selected agency.

**Comment by ClaireValdivia** [comment]
Confirming that this works as expected in staging
