### ISSUE TITLE
Reporting Period Management: Uploading Templates

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#20]
### Why is this issue important?

One of the epics of the CPF reporter is Reporting Period management. One of the stories within this epic is Uploading Templates for a Reporting Period. Building out this functionality is a necessary element of the CPF reporter. Dependent on [this ticket](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=44881845). The Reporting Periods tab and associated functionality should only be accessible to admin users.

### Current State

none

### Expected State

Clicking on the “Upload Template” button in a row of the Reporting Periods table should lead to the Upload Template page for the selected reporting period:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/fde3f850-c074-459d-832c-d3825f5a9251)

This page includes:

- Upload Period Template title
- “Choose file” button: opens the user’s files to select an upload file.
- “Cancel” button: clears chosen files and notes.
- “Upload” button: uploads the chosen report template for the period. 
  - Uploading a file is required. If no file is uploaded, an error message will appear under the missing field textboxes and the template will not be saved.

When the report has been uploaded, it should be stored for the tenant as the template for this period. This will be used in the Agency Reporting epic.

**Comment by ClaireValdivia** [comment]
Closing this as not a priority as most partners prefer to send the template to agency staff via email when the reporting period opens
