### ISSUE TITLE
Agency Report Submission - Support for spaces in filenames

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/cpf-reporter#201]
## Current State
Files are unable to be downloaded from S3 when they have spaces in their names.
Example error message: https://app.datadoghq.com/logs?query=service%3Acpf-reporter%20status%3Aerror&cols=host%2Cservice&event=AgAAAY7su1slOuyT9wAAAAAAAAAYAAAAAEFZN3N1MXVxQUFEWUlveTZnR0k0TUFBRAAAACQAAAAAMDE4ZWVjYzktMmE1Ny00Njc1LWFlZWUtZDQwNmRjZjI2YTE3&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1713362486311&to_ts=1713376886311&live=true

## Expected State
Spaces in filename is supported and does not cause any downstream errors.

**Comment by as1729** [comment]
@ClaireValdivia would it be important to ensure that the filename is consistent when the partner uploads the file and when it gets saved to their computer when they hit the Download button? I ask because of the level of effort difference is a bit higher to implement that functionality:

Example 1 (easy to implement):
- User uploads "My CPF File.xlsm"
- User is able to see in the front-end that their file is named "My CPF File.xlsm"
- User downloads the file and it gets saved into their computer as "abc123.xlsm" (Note: abc123 can be an alphanumeric code that we generate for the filename)

Example 2 (hard to implement):
- User uploads "My CPF File.xlsm"
- User is able to see in the front-end that their file is named "My CPF File.xlsm"
- User downloads the file and it gets saved into their computer as "My CPF File.xlsm". (Note: there is some evidence to suggest this is possible with our file-storage setup, but we will need to play around with it to get it right).

Example 3 (current state):
- USDR informs partners to _not_ use any spaces in their filenames
- User uploads "MyCPFFile.xlsm"
- User is able to see in the front-end that their file is named "MyCPFFile.xlsm"
- User downloads the file and it gets saved into their computer as "MyCPFFile.xlsm"

**Comment by ClaireValdivia** [comment]
@as1729 for the approach in example 1, would it add complexity for the alphanumeric code to follow a naming convention (i.e. upload_reportingperiodname_id, so it would be something like upload_quarter1_12

if that would be as complex as example 2 then I don't think it's worth it and we can move forward with the approach in Example 1 for now

**Comment by as1729** [comment]
@ClaireValdivia we can follow this naming convention: `upload_{quarter_name}_{upload_id}.xlsm` without too much extra effort.

**Comment by as1729** [comment]
@ClaireValdivia we were able to implement "Example 2" the filename that partners upload will be the same they will see when they download it.
