### ISSUE TITLE
Audit Report - version 1

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/cpf-reporter#21]
### Why is this issue important?

This is a critical functionality for partner administrators to QA the Excel workbooks that are submitted by agency staff users.

### Current State

No audit report exists

### Expected State

Administrators are able to generate an audit report from the UI.

The audit report will include the following sheets:
Project sheet

Project ID | Upload | Last Reported | Adopted Budget | Total Cumulative Obligations | Total Cumulative Expenditures | Current Period Obligations | Current Period Expenditures | Completion Status
-- | -- | -- | -- | -- | -- | -- | -- | --

### Implementation Plan

Example Input template added by @jcomeau1 
Example Audit report added by @jcomeau1

**Comment by snyde664** [comment]
checking if there is a subawards input template

**Comment by jcomeau1** [comment]
There is no subawards template or section within the guidance for them.

**Comment by ClaireValdivia** [comment]
closing as a duplicate of #82
