### ISSUE TITLE
2024-05-13 Milestone - Hide features that are not ready to ship

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/cpf-reporter#213]
## Context
On May 13th 2024 partners should be able to- 
1. login to `https://cpf.usdigitalresponse.org` with their own email-address
2. Be able to upload a workbook
3. See a list of workbooks uploaded
  - Staff users can only see workbooks they have themselves uploaded
  - Admin users can see all workbooks that have been uploaded within their organization
5. For each workbook, see if there are any validation errors
Any features not listed above should only be visible for users with the `USDR_ADMIN` role.

## Current State
There are several tabs/buttons/flows that are visible for all users. These need to be hidden.

## Expected State
The following tabs/buttons/flows are only visible to users with the role `USDR_ADMIN`.

1. Send Treasury/Audit Report button:
![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/6497366/fc798d8c-099e-4520-aca8-803e5a4bc4e4)

2. The following tabs - Agencies, Users, Subrecipients, Reporting Periods, Organizations
![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/6497366/0a397175-fbaa-4e0d-a991-4a8edb2afd0a)

3. "Validate" and "invalidate" buttons on the Upload Details page

**Comment by ClaireValdivia** [comment]
@Vikariusu can we also please hide the "Download Empty Template" button on the uploads page?

**Comment by Vikariusu** [comment]
@ClaireValdivia sure, will do!
