### ISSUE TITLE
2024-05-13 Milestone - Reporting Periods database changes

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/cpf-reporter#217]
## Current State
N/A

## Expected State
1. Add a `preferences` field to the `Organization` table. This field is `nullable` and is of type `JSONB`

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/6497366/f367483b-72c7-4b66-a901-6acd5e960336)

2. Ensure `ReportingPeriod` matches this structure

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/6497366/3b827db0-c586-48fb-8991-347fd41fc41b)

3. Ensure `ValidationRules` and `UploadValidation` tables are setup correctly.

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/6497366/b73d03b2-1d98-4c6a-945d-d8cf5975a51b)

**Comment by laurelkorwin** [comment]
Just confirming, the Enum for version should match the one in `schema.py` right? So:
```
enum Version {
  V2023_12_12
  V2024_01_07
  V2024_04_01
}
```

**Comment by laurelkorwin** [comment]
Also, assuming the `UploadValidation -> ValidationRules` relationship is 1:1?

**Comment by laurelkorwin** [comment]
Final step is making the changes to `ReportingPeriod`, reopening to do so
