### ISSUE TITLE
[Issue]: 5.24 Upload Validation Updates

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/cpf-reporter#287]
### Why is this issue important?
We received an updated version of the bulk import template from Treasury, so we made updates to the input template, which now need to be reflected in upload validation

### Expected State
Current Version number is now: v20240524

For all EC Codes (1A, 1B, 1C), the Project sheet has two new required fields:
- Subrecipient_UEI__c (new column E)
- Subrecipient_TIN__c (new column F)

EC Code 1A has a new optional field:
- Is_this_a_middle_mile_Project__c (this is a pick list field so no field type validation right now) (new column DV)

EC Codes 1B & 1C have new optional & conditional fields:
- Current_Program_Income_Earned__c  (new column DW)
- Current_Program_Income_Expended__c   (new column DX)
- Cumulative_Program_Income_Earned__c (new column DY)
- Cumulative_Program_Income_Expended__c (new column DZ)
- Program_Income_2_CFR__c (new column EA)
- Program_Income_2_CFR_Explanation__c (new column EB)

The Subrecipient sheet has a new optional field:
- Recipient_Profile_ID__c  (no additional validations needed right now) (new column D)

**New Validation Rules**
- Existing validation of template version should be updated to recognize v20240524 as the current version
- For all files, If a project row is missing a value for Subrecipient_UEI__c , an error should generate with an error message of: "Value is required for Subrecipient_UEI__c"
- For all files, if a project row is missing a value for Subrecipient_TIN__c, an error should generate with an error message of: "Value is required for Subrecipient_TIN__c"
- If the string entered for Subrecipient_UEI__c is not 12 characters, an error should generate with the error message: "Value for Subrecipient_UEI__c must be 12 characters"
- If the string entered for Subrecipient_TIN__c is not 9 characters, an error should generate with the error message: "Value for Subrecipient_TIN__c must be 9 characters"
- For the four new currency fields, value must be a number or currency symbol ("$" or ".") or they will receive an an error message that says "`Expected a currency value, but the value was [data entered]` Applies to: (Current_Program_Income_Earned__c,  
Current_Program_Income_Expended__c,    
Cumulative_Program_Income_Earned__c, 
Cumulative_Program_Income_Expended__c)
- Max length for currency fields is 15 characters
- for the field Recipient_Profile_ID__c - the type is string and the max length should be 100 characters 
- for Program_Income_2_CFR_Explanation__c, max length is 3000 characters - if it exceeds, message will be "`Value for [column name] cannot be longer than [column max length] (currently, [data indeed length])`

### Implementation Plan

The following functions need to be added...

**Comment by laurelkorwin** [comment]
@ClaireValdivia Do you have a sample of the excel file and / or more detail on which columns these new fields will be?

**Comment by laurelkorwin** [comment]
@ClaireValdivia Clarifying for `Program_Income_2_CFR_Explanation__c` -- the ticket says max 3000 characters but the sample template says 2000 -- should we go with the larger value?

**Comment by laurelkorwin** [comment]
Also @ClaireValdivia -- any guidance as to what the picklist values for `Program Income Pursuant` will be? If not, I can just make it a string for now with a placeholder comment

**Comment by ClaireValdivia** [comment]
@laurelkorwin thank you for catching these! 

- `Program_Income_2_CFR_Explanation__c`  - this was a typo on my part in the template - max 3000 characters is correct
- Currency fields should be max 15 characters
- For the picklist question - do you know if any picklist validations have been added already? My understanding was that picklist validations were a bit more complex so that we would hold off on implementing them. If there are some implemented already and it's not complicated to add, the options for `Program Income Pursuant` are Yes, No

**Comment by ClaireValdivia** [comment]
Tested in staging that I'm now able to access the uploads page and upload a file (note that there's a separate bug preventing full testing of the upload validation process, but will close this issue and address that separately - https://github.com/usdigitalresponse/usdr-gost/issues/3131)

**Comment by ClaireValdivia** [comment]
Been testing a bit today and so far, so good with the template updates!
