### ISSUE TITLE
[Issue]: Update text when upload does not pass validation

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/cpf-reporter#302]
### Why is this issue important?

Partners want clear differentiation in the uploads table and upload details page for when a file is validated, when it does not pass validation and (in the future), when a file is invalidated.

### Current State

If a file does not pass validation (i.e. has errors), the following display in both the "Validated?" column of the uploads table:  "Invalidated at [date], [time]"
In the upload details page, the following displays in the "Validation" row: "Invalidated on [date] [time] by [user's name]"

### Expected State

If upload does not pass validation (i.e. has errors), the Validated column in the uploads table should display the text "Did not pass validation on [date], [time].

In the upload details page, the following should display in red text next to the red circle with the white X: "Did not pass validation on [date] [time] by [user's name]"

### Implementation Plan

The following functions need to be added...

**Comment by Vikariusu** [comment]
@ClaireValdivia Just making sure - this ticket’s purpose is only to update the copy for invalid uploads regardless if the upload was invalidated by a user or didn’t pass validation? We currently don’t differentiate between uploads that didn’t pass validation and uploads that were manually invalidated, so the copy change will apply to both scenarios.

**Comment by ClaireValdivia** [comment]
@Vikariusu There is no feature implemented for a user invalidating an upload yet. Once we introduce the "Invalidate" feature, we will implement a different message for that scenario. that user story is described here - https://github.com/usdigitalresponse/cpf-reporter/issues/292
