### ISSUE TITLE
[Issue]: Treasury Report formatting in excel

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/cpf-reporter#480]
### Why is this issue important?
UPDATE - 10/17 - this is the same display as ARPA treasury reports, so this is low priority
While the treasury report csv file is saving data in the correct format, when you open a treasury report file in excel, the formatting does not render correctly, making it difficult to test

### Current State

When you open a treasury report csv file in excel, excel does not properly rending formatting such as:

- Dates do not show MM/DD/YYYY format, and instead display "10/1/24"
- currency does not consistently display two decimal places (i.e. we would expect 10.00 but it displays 10; we expect 15.10 but it displays 15.1)

### Expected State

- Dates should display as MM/DD/YYYY
- Currency should display as XX.XX even when values are zero

### Implementation Plan

The following functions need to be added...

**Comment by as1729** [comment]
@ClaireValdivia any chance you're able to attach a CSV that produces the Current State?

**Comment by boxydog** [comment]
Also, as we discussed in standup, could you post the poor-lookin date (from cpf) and the good-looking date (from arpa)? Maybe the difference in csv-s will be clear enough to act on.

**Comment by ClaireValdivia** [comment]
@boxydog apologies for the switch-up here, but I've confirmed this works the same as our treasury reports from ARPA so we'll deprioritize this one for now.

**Comment by boxydog** [comment]
Sounds good, thx.
