### ISSUE TITLE
Add Reporting periods during organization creation

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#58]
### Why is this issue important?
This is under the [Reporting Period management user story](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=50316086).
We need a script to create the default reporting periods for partners. 
Acceptance criteria: When a tenant is onboarded, when they navigate to the reporting period page there should already be a set of default reporting periods of quarters starting with Q4 (oct 1 - dec 31) of 2023. This first reporting period should be set as the current reporting period for new tenants.

### Current State

none

### Expected State

A ability to create default reporting periods available for all organizations

### Implementation Plan

When an organization has been created, immediately create a reporting period for that organization:
- Code will be added here to create reporting periods after this step: [createOrganization](https://github.com/usdigitalresponse/cpf-reporter/blob/main/api/src/services/organizations/organizations.ts#L19)
```
/*
  name             String
  startDate        DateTime       @db.Date
  endDate          DateTime       @db.Date
  organizationId   Int
  certifiedById    Int?
  inputTemplateId  Int
  outputTemplateId Int
  isCurrentPeriod  Boolean
*/
const input = {
    name: "Q4 2023"
}
db.reportingPeriod.create({
      data: input,
    })
```

**Comment by ClaireValdivia** [comment]
implementation details need to be updated. Not required for July

**Comment by ClaireValdivia** [comment]
closing based on convo with Aditya - we have an org creation script that is working
