### ISSUE TITLE
Agency Report Submission: Validation processing

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#61]
### Why is this issue important?

Part of [USER STORY: Agency Report Submission](https://github.com/usdigitalresponse/cpf-reporter/issues/73)

Sample json needed for completion, of both the templateRules.json as well as the upload validation. 

Acceptance criteria:

The previous step in the process should have taken an uploaded file to S3, ready for validation. This file should be a filled out version of [this excel macro enabled spreadsheet](https://docs.google.com/spreadsheets/d/1vfZXx2B8IttivEJqXjpfldS_w6pMgmIF/edit#gid=284311683). This ticket is to create the validation that will run on this spreadsheet. 

Validation can run on valid templates. **The specific validations and errors and their acceptance criteria can be found [here](https://docs.google.com/document/d/1SxqhtmHqXkXjlwFuaw12knaHumxSdHDgPQUQh8vJ5NA/edit#heading=h.5axicob0tchr).** The validation process will return errors or warnings as well as the location of the error in the uploaded template. 

### Implementation Plan

Entrypoint
- This is the current function that does validation for the ARPA reporter. https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/arpa_reporter/services/validate-upload.js#L582
- The setup does not need to be exactly the same as the above, but should accomplish similar things. Two things that may be helpful is:
  - `templateRules.json` file for CPF: https://github.com/usdigitalresponse/usdr-gost/blob/e13cf5fb746c4cd939e03d979c1f3f127f085955/packages/server/src/arpa_reporter/lib/templateRules.json
  - `templateDropdown.json` file for CPF: https://github.com/usdigitalresponse/usdr-gost/blob/e13cf5fb746c4cd939e03d979c1f3f127f085955/packages/server/src/arpa_reporter/lib/templateDropdowns.json
- The other input which is a persisted json version of the filled out workbook
  - Entrypoint is: https://github.com/usdigitalresponse/usdr-gost/blob/9d788b062fb5ad8ba8a75aa150c4a5ea14cac632/packages/server/src/arpa_reporter/services/records.js#L68C11-L68C11
  - The actual file that can be used for testing is here: https://github.com/usdigitalresponse/usdr-gost/blob/e13cf5fb746c4cd939e03d979c1f3f127f085955/packages/server/src/arpa_reporter/services/uploadFile.json
  - The raw version of the excel file can be found here: https://github.com/usdigitalresponse/usdr-gost/blob/e13cf5fb746c4cd939e03d979c1f3f127f085955/packages/server/__tests__/arpa_reporter/server/fixtures/upload.xlsm

The above data was generated in a branch in the `usdr-gost` code. This can be found here: https://github.com/usdigitalresponse/usdr-gost/compare/as/add-cpf-rules?expand=1

**Comment by ed-snodgrass** [comment]
@as1729 the uploadFile.json is missing version.

**Comment by ClaireValdivia** [comment]
Initial validations are implemented. Marking this as completed and additional issues will be opened as adjustments are needed to upload validation
