### ISSUE TITLE
Upload Results page

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#62]
### Why is this issue important?

this is part of the template upload feature, under [USER STORY: Agency Report Submission](https://github.com/usdigitalresponse/cpf-reporter/issues/73)

Acceptance criteria:

Given there are uploads in the upload table and the user is on the uploads page, when a user clicks on an upload in the upload table, it takes them to a page which displays the validation status as well as a table of versions of that upload. If the upload is invalid, a table of errors are displayed. 

### Current State

none

### Expected State

For uploads that pass validation, should look like the following:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/31436cb9-a401-4e07-a47d-a733e0f863f4)

for uploads that don't pass, table of errors found in validation should also be displayed:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/9374a5b3-6060-4b10-8c5f-7855d346c3f7)

### Implementation Plan

- Add the functionality to UploadCell.tsx and make sure it renders when the upload ID is passed into the URL.

**Comment by Vikariusu** [comment]
Created a draft PR for this feature here: https://github.com/usdigitalresponse/cpf-reporter/pull/88

**Comment by as1729** [comment]
Closing in favor of other issues we have already created to break this task down.
