### ISSUE TITLE
Login flow

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#9]
### Why is this issue important?
Under the [Login Flow User Story](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=50416332).

We want to have at least 1-2 pages built (agencies or uploads etc) so that volunteers have “golden examples” to look at and reference before jumping in. This should be done before volunteers start working on CPF reporter. 

### Current State

None

### Expected State

1-2 pages of CPF reporter webapp are built out and ready for use

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
From meeting - this is focused on login page, authentication, and get to homepage

**Comment by as1729** [comment]
https://github.com/usdigitalresponse/cpf-reporter/pull/50
