### ISSUE TITLE
Login Flow: customize login email from Passage

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#94]
### Why is this issue important?

This is part of the [Login Flow User Story](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=50416332). Currently, our login code email design is set as the Passage default. We want to customize this to reflect the USDR logo and CPF Tool name.

### Current State

Passage default email design

### Expected State

The login code email is updated to incorporate the USDR Logo and CPF Reporter name.

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
closing this for now as it's not a priority and design/requirements work would still be needed
